language: java
sudo: required

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer # https://docs.travis-ci.com/user/languages/java/#Updating-Oracle-JDK-to-a-recent-release
    - jdk: oraclejdk10
      addons:
        apt:
          packages:
            - oracle-java10-installer # https://docs.travis-ci.com/user/languages/java/#Updating-Oracle-JDK-to-a-recent-release

notifications:
  email: false
