# Nazwy komend
commands:
  guild: 
    name: 'gildia'
    aliases:
    - 'gildie'
    - 'g'
  create:
    name: 'zaloz'
    aliases: []
  delete:
    name: 'usun'
    aliases: []
  confirm:
    name: 'potwierdz'
    aliases: []
  invite:
    name: 'zapros'
    aliases: []
  join:
    name: 'dolacz'
    aliases: []
  leave:
    name: 'opusc'
    aliases: []
  kick:
    name: 'wyrzuc'
    aliases: []
  base: 
    name: 'baza'
    aliases: []
  enlarge: 
    name: 'powieksz'
    aliases: []
  ally: 
    name: 'sojusz'
    aliases: []
  break: 
    name: 'rozwiaz'
    aliases: []
  info: 
    name: 'info'
    aliases: []
  player: 
    name: 'gracz'
    aliases: []
  top: 
    name: 'top'
    aliases:
    - 'top10'
  validity:
    name: 'przedluz'
    aliases: []
  leader:
    name: 'lider'
    aliases:
    - 'zalozyciel'
  deputy:
    name: 'zastepca'
    aliases: []
  ranking: 
    name: 'ranking'
    aliases: []

  setbase:
    name: 'ustawbaze'
    aliases:
    - 'ustawdom'
  pvp:
    name: 'pvp'
    aliases:
    - 'ustawpvp'

  # Komendy administratora
  admin:
    main: 'ga'
    add: 'ga dodaj'
    delete: 'ga usun'
    kick: 'ga wyrzuc'
    teleport: 'ga tp'
    points: 'ga points'
    kills: 'ga kills'
    deaths: 'ga deaths'
    ban: 'ga ban'
    lives: 'ga zycia'
    move: 'ga przenies'
    unban: 'ga unban'
    validity: 'ga przedluz'
    name: 'ga nazwa'

# Dane wymagane do polaczenia z baza
mysql:
  hostname: localhost
  port: 3306
  database: db
  user: root
  password: passwd
  poolSize: 16
  
# Config Version
version: 3.9.9.9 Cleaned
