#~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~#
#                               #
#          FunnyGuilds          #
#        1.5.7 Sweetness        #
#                               #
#~-~-~-~-~-~-~-~-~-~-~-~~-~-~-~~#

# Maksymalna dlugosc nazwy gildii
name-length: 22
# Minimalna dlugosc nazwy gildii
name-min-length: 4
# Maksymalna dlugosc tagu gildii
tag-length: 4
# Minimalna dlugosc tagu gildii
tag-min-length: 2
# Przedmioty wymagane do zalozenia gildii
items:
- 5 stone
- 5 dirt
# Odleglosc od spawnu
create-distance: 100
# Blok, jaki pojawi sie pod nami po stworzeniu gildii
create-material: bedrock
# Wielkosc regionu gildii
region-size: 50
# Minimalna odleglosc miedzy terenami gildii
region-min-distance: 10

# Mozliwosc powiekszania gildii
enlarge-enable: true
# O ile powieksza teren gildii 1 poziom
enlarge-size: 5
# Koszt powiekszania gildii (kazdy myslnik, to 1 poziom gildii)
enlarge-items:
- 8 diamond
- 16 diamond
- 24 diamond
- 32 diamond
- 40 diamond
- 48 diamond
- 56 diamond
- 64 diamond
- 72 diamond
- 80 diamond

# Maxymalna ilosc czlonkow w gildii
invite-members: 15

# Czas wyswietlania powiadomienia na pasku powiadomien (w sekundach)
region-notification-time: 15
# Co ile moze byc wywolywany pasek powiadomien przez jednego gracza (w sekundach)
region-notification-cooldown: 60
# Przez ile sekund nie mozna budowac na terenie gildii po wybuchu
region-explode: 120

# Wyglad tagu osob w gildii
prefix-our: '&a{TAG}&f '
# Wyglad tagu gildii sojuszniczej
prefix-allies: '&6{TAG}&f '
# Wyglad tagu wrogiej gildii
prefix-enemies: '&c{TAG}&f '
# Wyglad tagu gildii neutralnej (widziany rowniez przez graczy bez gildii)
prefix-other: '&7{TAG}&f '

# Wyglad znaczika {TAG} wstawionego w format chatu
chat-guild: '&2{TAG}'
# Wyglad znaczika {RANK} wstawionego w format chatu
chat-rank: '&2{RANK}'
# Wyglad znaczika {POINTS} wstawionego w format chatu
chat-points: '&2{POINTS}'

# Symbol od ktorego zaczyna sie wiadomosc do gildii/sojusznikow/wszystkich gildii
chat-priv: '!'
chat-ally: '!!'
chat-global: '!!!'
# Wyglad wiadomosci wysylanej na czacie gildii.
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-priv-design: '&8[&aChat gildii&8] &7{PLAYER}&8:&f {MESSAGE}'
# Wyglad wiadomosci wysylanej na czacie sojusznikow dla sojusznikow.
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-ally-design: '&8[&6Chat sojuszniczy&8] &8{TAG} &7{PLAYER}&8:&f {MESSAGE}'
# Wyglad wiadomosci wysylanej na czacie globalnym gildii.
# Zmienne: {PLAYER}, {TAG}, {MESSAGE}
chat-global-design: '&8[&cChat globalny gildii&8] &8{TAG} &7{PLAYER}&8:&f {MESSAGE}'

# Ranking od ktorego rozpoczyna gracz
rank-start: 1000
# Jaki procent punktow zabitego ma przyznawac zabojcy
rank-percent: 2

# Czy czlonkowie gildii moga sobie zadawac obrazenia
damage-guild: false
# Czy sojuszniczy moga sobie zadawac obrazenia
damage-ally: false

# Mozliwosc teleportacji do gildii
base-enable: true
# Czas oczekiwania na teleportacje (w sekundach)
base-delay: 5
# UWAGA: Platonosc za teleportacje jeszcze nie zostala napisana
# Koszt teleportacji do gildii (jezeli brak, wystarczy zrobic: base-items: [])
base-items:
- 1 diamond
- 1 emerald

# Wyglad listy graczy. Przedzial od 1 do 60
# Limit znakow: 30
# > Spis zmiennych:
# {ONLINE} - Liczba graczy online
# {PLAYER} - Gracz
# {PING} - Ping
# {TPS} - TPS
# {GUILD} - Gildia
# {TAG} - Tag gildii
# {POINTS} - Punkty
# {KILLS} - Zabojstwa
# {DEATHS} - Smierci
# {SECOND} - Sekunda
# {MINUTE} - Minuta
# {HOUR} - Godzina
# {PTOP-<pozycja>} - Gracz na podanym miejscu w rankingu
# {GTOP-<pozycja>} - Gildia na podanej pozycji w rankingu
player-list:
  1: '&7Nick: &b{PLAYER}'
  2: '&7Ping: &b{PING}'
  3: '&7TPS: &b{TPS}'
  
  4: '&7Punkty: &b{POINTS}'
  5: '&7Zabojstwa: &b{KILLS}' 
  6: '&7Smierci: &b{DEATHS}'
  
  7: '&7Godzina: &b{HOUR}'
  8: '&7Minuta: &b{MINUTE}'
  9: '&7Sekunda: &b{SECOND}'
  
  10: '&7Online: &b{ONLINE}'
  11: '&7Gildia: &b{GUILD}'
  
  23: '&bTop 3 Gildii'
  
  25: '&71. &b{GTOP-1}'
  26: '&72. &b{GTOP-2}'
  27: '&73. &b{GTOP-3}'
  
  32: '&bTop 3 Graczy'
  
  34: '&71. &b{PTOP-1}'
  35: '&72. &b{PTOP-2}'
  36: '&73. &b{PTOP-3}'

# Tablista wlaczona
player-list-enable: true
# Co ile sekund ma odswiezac liste graczy
player-list-interval: 1
# Ping wyswietlany na tab
player-list-ping: 0
# Jezeli buguje Ci sie tablista
# - Po wejsciu gracza wszystko sie rozjezdza
# Wlacz ta opcje
player-list-patch: false

# Nazwy komend (na razie bez wsparcia subkomend)
commands:
  create: 'zaloz'
  delete: 'usun'
  confirm: 'potwierdz'
  invite: 'zapros'
  join: 'dolacz'
  leave: 'opusc'
  kick: 'wyrzuc'
  base: 'baza'
  enlarge: 'powieksz'
  guild: 'gildia'
  g: 'g'
  ally: 'sojusz'
  break: 'rozwiaz'
  player: 'gracz'
  top: 'top'
  
  admin:
    main: 'ga'
    add: 'ga dodaj'
    delete: 'ga usun'
    kick: 'ga wyrzuc'
    teleport: 'ga tp'
    points: 'ga points'
    kills: 'ga kills'
    deaths: 'ga deaths'
    
  
# Co ile minut ma automatycznie zapisywac dane
data-interval: 1
# Typ zapisu danych
# Flat - Lokalne pliki
# MySQL - baza danych 
data-type:
  flat: true
  mysql: false
# Dane wymagane do polaczenia z baza
mysql:
  hostname: localhost
  port: 3306
  database: db
  user: root
  password: passwd

# Utils
patch-scoreboard: true
mcstats: true
debug: true
